### ISSUE TITLE
New release due to Axios vulnerability

### ISSUE THREAD

**Issue by thewilkybarkid** [ukalwa/scholarly#146]
Would it be possible to have a new release to remove the vulnerable version of Axios being used? (This was fixed in #78.)

**Comment by ukalwa** [comment]
Thanks for the issue. New version is published now, please check :)

**Comment by ukalwa** [comment]
Ah, looks like I was on a wrong branch when I published it. Let me publish `v1.1.1`. Thanks for checking 👍

**Comment by thewilkybarkid** [comment]
Great, thanks!
